### PR TITLE
[Shared] Updated Stat Port for HAProxy

### PR DESCRIPTION
**Pull request by sauveergoel**
Signed-off-by: sauveergoel <sauveer.goel@accenture.com>

**Changelog**
- Updated Stat Port for HAProxy

**Reviewed by**
@abevers @lakshyakumar @sownak 

**Linked issue**
#1120

### CODE REVIEW

**Comment by abevers** [comment]
Which platform did you use to test this? I remember I had some connection issues when testing this with Hyperledger Fabric

**Comment by sauveergoel** [comment]
> Which platform did you use to test this? I remember I had some connection issues when testing this with Hyperledger Fabric

@lakshyakumar  tested it on Fabric

**Comment by sownak** [comment]
Has this been tested end-2-end?

**Comment by sauveergoel** [comment]
> Has this been tested end-2-end?

till the chaincode instantiation

**Pull request merged**
