### PR TITLE
[ Corda-Ent ] Update documentation for Corda Enterprise configuration

### LINKED ISSUE #1037: Update readme.md of each role for Enterprise Corda platform
### Description
As a developer I want to update all the readme.md under each role so that we have proper description for roles. 
The readme can be found at r3-corda-ent/configuration/roles/TYPE_OF_ROLE/ROLE_NAME/Readme.md

### Acceptance Criteria
1. All Readme.md should reflect the latest code for each role

### PR DESCRIPTION
**Pull request by abevers**
Signed-off-by: Arnoud Bevers <arnoud.bevers@accenture.com>

**Changelog**
- Update documentation for the `platforms/r3-corda-ent/configuration`
- All employ the same structure
- Added documentation for roles that were not previously documented

**To be reviewed by**
@suvajit-sarkar 

**Linked issue**
Resolves #1037

### CODE REVIEW

**Review by sownak — APPROVED** [review]
LGTM. Please raise a pr for helm3 branch as well

**Review by jagpreetsinghsasan — COMMENTED** [review]
For the helm3 branch, this should be relooked as the helm3 branch has different code. Infact, this PR should be created on Helm3 branch only

**Comment by abevers** [comment]
> 
> 
> LGTM. Please raise a pr for helm3 branch as well

@sownak what is the best strategy on this? Merge `feature/helm3` into my local `feature/1037-cordaent-docs` branch and then create PR? Or wait for this PR to be merged first?

**Comment by sownak** [comment]
> t i

Create a separate branch from helm3 and add your changes and raise a PR.

**Pull request merged**
