### PR TITLE
[corda] implemented new test for reset-network roles

### PR DESCRIPTION
**Pull request by mgCepeda**
Signed-off-by: mgCepeda <marina.gomez.cepeda@accenture.com>

**Changelog**
- Add new test for reset-network roles
- Fixed task using molecule-idempotence-notest tag to be able to run the implemented test

 

**Reviewed by**
@suvajit-sarkar
@alvaropicazo 

 

**Linked issue**
#628

### CODE REVIEW

**Review by jagpreetsinghsasan — CHANGES_REQUESTED** [review]
Needs substantial changes.
The reset-network molecule tests should first create dummy resources (like gitops release files) and converge.yml should delete them and verify.yml should verify if those dummy resources are deleted. Then only the reset-network molecule test is verify-able.

**Comment by mgCepeda** [comment]
> Good quick work 👍
> But the PR needs substantial changes.
> The reset-network molecule tests should first create dummy resources (like gitops release files) and converge.yml should delete them and verify.yml should verify if those dummy resources are deleted. Then only the reset-network molecule test is verify-able.

**Comment by mgCepeda** [comment]
> Good quick work 👍
> But the PR needs substantial changes.
> The reset-network molecule tests should first create dummy resources (like gitops release files) and converge.yml should delete them and verify.yml should verify if those dummy resources are deleted. Then only the reset-network molecule test is verify-able.

Thanks!! I'm working in it

**Review by sownak — CHANGES_REQUESTED** [review]
remove the empty file

**Review by suvajit-sarkar — APPROVED** [review]

**Comment by sownak** [comment]
Please remove `platforms/r3-corda/configuration/{changed:` file. Check why it is getting created as well

**Pull request merged**
