### PR TITLE
BAF docker build #210

### PR DESCRIPTION
**Pull request by suvajit-sarkar**
#210

### CODE REVIEW

**Comment by suvajit-sarkar** [comment]
> I think this needs a readthedocs readme under developer guide (similar to mac one). It is not very clear like where the network.yaml should be stored.

Yes I plan to add that

**Comment by jagpreetsinghsasan** [comment]
The repo cloning/pushing to the container is not mentioned or not clear.

**Comment by sownak** [comment]
> The repo cloning/pushing to the container is not mentioned or not clear.

This should be now clear in the developer guide readme

**Comment by jagpreetsinghsasan** [comment]
It's fine now

**Pull request merged**
